In [1]:
%run testify.py

Read DMNAO NAOAO matrixs in nbofile OK!


In [2]:
np.set_printoptions(precision=4, suppress=True)

In [35]:
occ,vec = np.linalg.eig(DMNAO)

In [36]:
occ = np.real(occ)
occ1 = occ[1]
occ1

2.0000724793377325

In [37]:
vec = np.real(vec)
vec1 = vec[:,1]
vec1

array([ 0.1269,  0.435 , -0.3971,  0.0001, -0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    , -0.0875,  0.0884, -0.    ,
        0.    ,  0.    ,  0.    ,  0.    , -0.005 , -0.7884, -0.0014])

In [106]:
yy
np.outer(yy,yy)

array([[ 0.0397,  0.0883, -0.1742],
       [ 0.0883,  0.1963, -0.3872],
       [-0.1742, -0.3872,  0.764 ]])

In [109]:
a = np.array([1,2,3])
b = np.array([-1,0,1])
np.outer(a,b)

array([[-1,  0,  1],
       [-2,  0,  2],
       [-3,  0,  3]])

In [110]:
np.outer(b,a)

array([[-1, -2, -3],
       [ 0,  0,  0],
       [ 1,  2,  3]])