In [2]:
%run testify.py

Read DMNAO NAOAO matrixs in nbofile OK!


In [3]:
np.set_printoptions(precision=4, suppress=True)

In [4]:
occ,vec = np.linalg.eig(DMNAO)

In [5]:
np.real(occ)

array([ 1.9999,  2.0001,  2.    ,  2.    ,  2.    ,  2.    ,  0.0001,
       -0.0001,  0.    ,  0.    , -0.    , -0.    , -0.    , -0.    ,
       -0.    ,  0.    ,  0.    , -0.    , -0.    ,  0.    , -0.    ])

In [6]:
X = np.real(vec)

In [12]:
for i in range(21):
    for j in range(21):
        print("{:.4f} ".format(float(X[i,j])),end='')
    print("\n")

0.0597 0.1269 0.9854 -0.0968 0.0000 -0.0000 -0.0000 -0.0000 0.0001 -0.0000 0.0000 0.0000 0.0000 -0.0000 0.0000 -0.0000 -0.0000 -0.0000 0.0000 0.0000 0.0000 

0.7894 0.4350 -0.0617 0.4287 -0.0000 0.0000 0.0011 0.0046 0.0009 -0.0014 0.0015 0.0035 0.0000 -0.0000 0.0000 -0.0000 -0.0000 -0.0000 0.0000 0.0000 0.0000 

0.1676 -0.3971 0.0510 0.1017 -0.0000 0.0000 0.6393 -0.4545 -0.1531 -0.0750 0.0417 0.3940 0.0000 -0.0000 -0.0000 0.0000 0.0000 0.0000 -0.0000 0.0000 0.0000 

-0.0008 0.0001 0.0002 0.0014 -0.0000 -0.0000 0.1337 0.1444 0.2226 0.4228 -0.7075 0.1915 0.0000 0.0000 -0.4424 0.0000 0.0000 0.0000 -0.0001 0.0000 0.0000 

0.0003 -0.0000 -0.0001 -0.0006 0.0000 -0.0000 -0.0028 -0.0344 -0.1197 -0.3100 0.2768 -0.1700 -0.0000 0.0000 -0.8848 0.0001 0.0001 0.0001 -0.0001 0.0000 0.0000 

-0.0000 0.0000 0.0000 0.0000 -1.0000 0.0091 0.0000 -0.0000 0.0000 0.0000 -0.0000 -0.0000 0.0038 -0.0012 0.0000 -0.0000 -0.0000 -0.0000 0.0000 0.0000 0.0000 

-0.0000 0.0000 0.0000 0.0000 -0.0010 0.0000 -0.0000 -0.

In [24]:
from scipy.sparse import linalg 

In [34]:
occ2,vec2=linalg.eigs(DMNAO,21)

c:\devapps\python37\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py:1269: RuntimeWarning: k >= N - 1 for N * N square matrix. Attempting to use scipy.linalg.eig instead.
  RuntimeWarning)


In [35]:
occ2

array([ 1.9999+0.j,  2.0001+0.j,  2.    +0.j,  2.    +0.j,  2.    +0.j,
        2.    +0.j,  0.0001+0.j, -0.0001+0.j,  0.    +0.j,  0.    +0.j,
       -0.    +0.j, -0.    +0.j, -0.    +0.j, -0.    +0.j, -0.    +0.j,
        0.    +0.j,  0.    -0.j, -0.    +0.j, -0.    +0.j,  0.    +0.j,
        0.    +0.j])

In [36]:
np.real(vec2)

array([[ 0.0597,  0.1269,  0.9854, -0.0968,  0.    , -0.    , -0.    ,
        -0.    ,  0.0001, -0.    ,  0.    ,  0.    ,  0.    , -0.    ,
         0.    , -0.    , -0.    , -0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.7894,  0.435 , -0.0617,  0.4287, -0.    ,  0.    ,  0.0011,
         0.0046,  0.0009, -0.0014,  0.0015,  0.0035,  0.    , -0.    ,
         0.    , -0.    , -0.    , -0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.1676, -0.3971,  0.051 ,  0.1017, -0.    ,  0.    ,  0.6393,
        -0.4545, -0.1531, -0.075 ,  0.0417,  0.394 ,  0.    , -0.    ,
        -0.    ,  0.    ,  0.    ,  0.    , -0.    ,  0.    ,  0.    ],
       [-0.0008,  0.0001,  0.0002,  0.0014, -0.    , -0.    ,  0.1337,
         0.1444,  0.2226,  0.4228, -0.7075,  0.1915,  0.    ,  0.    ,
        -0.4424,  0.    ,  0.    ,  0.    , -0.0001,  0.    ,  0.    ],
       [ 0.0003, -0.    , -0.0001, -0.0006,  0.    , -0.    , -0.0028,
        -0.0344, -0.1197, -0.31  ,  0.2768, -0.17  , -0.    ,  0.    ,
  