In [1]:
%run tip.py

Read DMNAO NAOAO matrixs in nbofile OK!


In [2]:
np.set_printoptions(precision=4, suppress=True)

In [4]:
Na = DMNAO[:19,:19].copy()
H = DMNAO[-2:,-2:].copy()

In [5]:
lambNA,vecNA = np.linalg.eig(Na)
lambH,vecH = np.linalg.eig(H)

In [6]:
lambNA

array([ 0.4144+0.j, -0.    +0.j,  0.    +0.j, -0.    +0.j,  0.    +0.j,
        1.9999+0.j,  2.    +0.j,  2.    +0.j, -0.    +0.j, -0.    +0.j,
        2.    +0.j,  2.    +0.j, -0.    +0.j,  0.    +0.j, -0.    +0.j,
        0.    +0.j,  0.    -0.j,  0.    +0.j, -0.    +0.j])

In [14]:
np.real(lambNA)

array([ 0.4144, -0.    ,  0.    , -0.    ,  0.    ,  1.9999,  2.    ,
        2.    , -0.    , -0.    ,  2.    ,  2.    , -0.    ,  0.    ,
       -0.    ,  0.    ,  0.    ,  0.    , -0.    ])

In [30]:
X = np.real(vecNA)

In [23]:
X_inv = np.linalg.inv(X)

In [25]:
E = X_inv@Na@X

In [28]:
np.array([E[i,i] for i in range((E.shape)[0])])

array([ 0.4144, -0.    ,  0.    , -0.    ,  0.    ,  1.9999,  2.    ,
        2.    , -0.    ,  0.    ,  2.    ,  2.    , -0.    , -0.    ,
       -0.    , -0.    ,  0.    ,  0.    ,  0.    ])

In [61]:
X[:,1]

array([ 0.    ,  0.0042, -0.172 ,  0.4476, -0.1958, -0.    ,  0.    ,
        0.    , -0.    ,  0.    ,  0.    ,  0.0048, -0.7998,  0.2304,
        0.    ,  0.    ,  0.    ,  0.    , -0.1973])

In [59]:
np.sum(X[:,0]**2)

1.0000000000000002

array([1, 4, 9], dtype=int32)